### ISSUE TITLE
news: what is this sorcery!?

### ISSUE THREAD

**Issue by phdsg** [raincheque/qwelk#3]
wow man, this is wicked. i know, it's still not released, but i want some info please. this beast is awesome.
i also checked out indra. i'm really stunned. outstanding work.

**Comment by raincheque** [comment]
@phdsg thank you, i'm really happy you like them.
NEWS is kind of a cardinal (that's where it get its name from: North East West South) cellular automaton which decodes the input signal into directions and blits it! I'm adding a HOLD input to it which would make it less jumpy and diverse. I have also tried it as an oscillator in !(gatemode) and clocked in very slow rates have gotten some pretty wicked results! be sure to check it out! I will upload the old visual version of this cardinal automaton soon and will send you a link.
I would like to ask your opinion about Indra's instability. I quickly put it together and never stabilized/sync'ed its osc's so there's a drift and no aliasing in there for obvious reasons. But the more I fool around with it the more I like it as it is and I find it really hard to sterilize it. I was considering just releasing it as it as, since there are many 'perfect' modules out there. Would you consider this osc a finished toy? also I love using it as an LFO, just feed some negative (DC) signal into FM and crank it up and you have a cool LFO with waveshaping etc.. There's an individual output attention option in its context menu too if you haven't noticed.

**Comment by phdsg** [comment]
haven't dug too deep into it.
just had a quick run to see what it does. this was my little setup:

![qwelk](https://user-images.githubusercontent.com/33329578/34056540-aae7e700-e1d3-11e7-95b6-4180ef8a6ba0.PNG)
managed to find an input for every one of news' outputs. and routed indras oscs back into it's fm input via the seq. switch.
and it made the weirdest glitchy things and i was happy.
had it running in the background for a while, but then had to work a little bit on my own modules.
will probably have a play with it again over the weekend.

edit: i'll try some more melodic stuff and set it up manually instead of just ctrl-r ing till it sounds wicked.
also gonna try the other options you mentioned.

maybe you can just add the sterile mode as a menuoption...

**Comment by raincheque** [comment]
HA that patch looks wicked! exactly the kind of stuff i was aiming for! are you uploading sounds anywhere?
that's a good idea I should stop slacking off and do it.

**Comment by phdsg** [comment]
i uploaded one patch to patchstorage a while ago to test the platform. other than that, no.
too busy/distracted with other stuff.

**Comment by phdsg** [comment]
ok, just started to play around with indra...
first, had a couple of crashes/hangs, but when starting a fresh patch couldn't reproduce :/

cv inputs under the amp are not working for me.

**Comment by raincheque** [comment]
crashes and hangs were probably caused by the added input & param (the top, rightmost input & knob). so when you loaded old patched everything was patched up wrong. sorry but this is not a release so things change all the time. cv inputs work, if you are using individual outputs instead of the sum output, make sure you have the  'Attenuate Component Outs' ticked under Indra's context menu when you rclick on it. that way individual out levels are affected by faders & cv.

**Comment by phdsg** [comment]
oh i missed that. trying again.
man, this thing makes HARD KICKS.

as for the crashes, i didn't have indra in that patch before, so it's probably something else.

**Comment by phdsg** [comment]
![qwelk](https://user-images.githubusercontent.com/33329578/34082348-a47476ce-e35c-11e7-9f08-2db27086aeaf.gif)

cv effect is almost unnoticable.

**Comment by raincheque** [comment]
that's probably because it's slewed to fuck in that patch! the little knob right above the input which you have cranked up is the gate slew, try reducing it or setting it to zero and start from there.
As for the crashes, I have changed NEWS lots, added a hold input, bipolar bit wrap and slew on the outs so that may be it. if you found anything else please let me know. 
I should really adjust that gate slew on indra though ;) thanks for the feedback man I appeciate it!

**Comment by phdsg** [comment]
oh damn.  and i thought that would the attenuator for the cv input :) thx 4 explaining.
haven't tried the new news yet...

**Comment by phdsg** [comment]
sooo... indra... will it be released?

**Comment by raincheque** [comment]
hopefully. might release it as is cause I'm SUPER busy atm.
